# Generated by Django 6.0.2 on 2026-05-12 07:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('industry', models.CharField(max_length=120)),
                ('location', models.CharField(max_length=180)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('objectives', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='active', max_length=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='placements', to='internships.company')),
            ],
            options={
                'ordering': ['-start_date', 'student__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('evaluator_name', models.CharField(max_length=140)),
                ('evaluator_role', models.CharField(choices=[('academic', 'Academic Supervisor'), ('industry', 'Industry Supervisor')], max_length=20)),
                ('period', models.CharField(default='Midterm', max_length=80)),
                ('professionalism', models.PositiveSmallIntegerField(default=0)),
                ('technical_skill', models.PositiveSmallIntegerField(default=0)),
                ('communication', models.PositiveSmallIntegerField(default=0)),
                ('problem_solving', models.PositiveSmallIntegerField(default=0)),
                ('attendance', models.PositiveSmallIntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=20)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='internships.placement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('offer_letter', 'Offer Letter'), ('logbook', 'Logbook'), ('evaluation', 'Evaluation'), ('report', 'Final Report')], max_length=30)),
                ('title', models.CharField(max_length=180)),
                ('file_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='internships.placement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('registration_no', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('year_of_study', models.PositiveSmallIntegerField(default=3)),
                ('status', models.CharField(choices=[('pending', 'Pending Placement'), ('placed', 'Placed'), ('active', 'Active'), ('completed', 'Completed'), ('flagged', 'Flagged')], default='pending', max_length=20)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='internships.department')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='placement',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='internships.student'),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('role', models.CharField(choices=[('academic', 'Academic Supervisor'), ('industry', 'Industry Supervisor')], max_length=20)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.company')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.department')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='placement',
            name='academic_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'academic'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_placements', to='internships.supervisor'),
        ),
        migrations.AddField(
            model_name='placement',
            name='industry_supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'industry'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='industry_placements', to='internships.supervisor'),
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheduled_for', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('missed', 'Missed')], default='scheduled', max_length=20)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='internships.placement')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='internships.supervisor')),
            ],
            options={
                'ordering': ['scheduled_for'],
            },
        ),
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveSmallIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=180)),
                ('activities', models.TextField()),
                ('skills_gained', models.TextField(blank=True)),
                ('challenges', models.TextField(blank=True)),
                ('hours_worked', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('rejected', 'Needs Revision')], default='draft', max_length=20)),
                ('supervisor_feedback', models.TextField(blank=True)),
                ('placement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='internships.placement')),
            ],
            options={
                'verbose_name_plural': 'log entries',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('placement', 'week_number', 'date')},
            },
        ),
    ]
